language: go

go:
  - "1.11.4"

os:
  - linux

dist: xenial

services:
  - postgresql

addons:
  postgresql: "11"
  apt:
    packages:
    - postgresql-11
    - postgresql-client-11

env:
  global:
    - PGPORT=5433
    - DB_URL=postgres://user:password@127.0.0.1:5433/devlover-id?sslmode=disable
    - CGO_ENABLED=0
    - GO111MODULE=on

cache: bundler

install:
  - sudo apt-get update
  - sudo apt-get install -y ruby ruby-dev libpq-dev
  - cd database && gem install bundle && bundle install && cd ..

before_script:
  - psql -c "create role \"user\" with login createdb password 'password';"
  - psql -c "create database \"devlover-id\" with owner 'user';"

script:
  - make test-db
  - make test-api
