language: go

go:
  - "1.11.*"

os:
  - linux

dist: xenial

services:
  - postgresql

addons:
  postgresql: "11"

env:
  - DB_URL=postgres://postgres@localhost/devlover-id?sslmode=disable
  - CGO_ENABLED=0
  - GO111MODULE=on

install:
  - sudo apt-get update
  - apt-get install -y ruby ruby-dev libpq-dev
  - gem install bundle
  - bundle install

before_script:
  - psql -c 'create database "devlover-id";' -U postgres

script:
  - rake db:drop
  - rake db:create
  - rake db:migrate
  - make test-api
