language: go

go:
  - "1.11.*"

os:
  - linux

dist: xenial

services:
  - postgresql

addons:
  postgresql: "11"

env:
  global:
    - DB_URL=postgres://postgres@localhost/devlover-id?sslmode=disable
    - CGO_ENABLED=0
    - GO111MODULE=on

install:
  - sudo apt-get update
  - sudo apt-get install -y ruby ruby-dev libpq-dev
  - cd database && gem install bundle && bundle install

before_script:
  - psql -c 'create database "devlover-id";' -U postgres

script:
  - make test
