steps:
- name: 'docker/compose:1.23.2'
  args: ['up', '-d']
- name: 'ruby:2.5'
  entrypoint: 'bash'
  args: ['-x', 'build/test_db.sh']
  env:
    - 'DB_URL=postgres://user:password@database/devlover-id?sslmode=disable'
- name: 'golang:1.11'
  entrypoint: 'sh'
  args: ['-x', 'build/test_api.sh']
  env:
    - 'CGO_ENABLED=0'
    - 'GO111MODULE=on'
    - 'DB_URL=postgres://user:password@database/devlover-id?sslmode=disable'
