steps:
- name: 'docker/compose:1.23.2'
  args: ['up', '-d']

- name: 'ruby:2.5'
  entrypoint: 'bash'
  args: ['-x', 'build/test_db.sh']
  env:
    - 'DB_URL=postgres://user:password@database/devlover-id?sslmode=disable'

- name: 'golang:1.11'
  entrypoint: 'sh'
  args: ['-x', 'build/test_api.sh']
  env:
    - 'CGO_ENABLED=0'
    - 'GO111MODULE=on'
    - 'DB_URL=postgres://user:password@database/devlover-id?sslmode=disable'

- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=.ssh/id_rsa.enc
  - --plaintext-file=.ssh/id_rsa
  - --location=global
  - --keyring=gcb
  - --key=gcb-secrets
- name: alpine:3.8
  args: ['sh', '-x', 'build/deploy.sh']
  env:
    - 'STAGING_HOST=$_STAGING_HOST'
