version: 2
jobs:
  test_db:
    docker:
      - image: ruby:2.5-alpine
        environment:
          DB_URL: postgres://user:password@localhost/db?sslmode=disable
      - image: postgres:11
        environment:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: db
    steps:
      - checkout
      - run: |
          apk add --repository=http://dl-cdn.alpinelinux.org/alpine/edge/main postgresql-client postgresql-dev
          apk add ruby-dev build-base
          sh -x -e ./build/test_db.sh
  test_api:
    docker:
      - image: golang:1.11-alpine
        environment:
          DB_URL: postgres://user:password@localhost/db?sslmode=disable
          CGO_ENABLED: 0
      - image: postgres:11
        environment:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: db
    steps:
      - checkout
      - run: apk add --no-cache postgresql-client git
      - run: psql $DB_URL -f ./database/db/structure.sql
      - run: sh ./build/test_api.sh
workflows:
  version: 2
  tests:
    jobs:
      - test_db
      - test_api
