# frozen_string_literal: true

require 'active_record_migrations'

ActiveRecordMigrations.configure do |c|
  c.database_configuration = {
    'default' => {
      'url' => ENV['DB_URL'] || 'postgres://postgres:@localhost:5432/develover?sslmode=disable'
    }
  }
  c.environment = 'default'
  c.migrations_paths = ['migrations']
end
ActiveRecordMigrations.load_tasks
